Bootstrap: docker
From: pytorch/pytorch:2.5.1-cuda11.8-cudnn9-devel

%post
    # Install system dependencies
    apt-get update && apt-get install -y \
        git \
        wget \
        build-essential \
        libgl1-mesa-dev \
        libglu1-mesa-dev \
        freeglut3-dev \
        libglew-dev \
        libglfw3-dev \
        libegl1-mesa-dev \
        libgbm-dev \
        libgles2-mesa-dev \
        mesa-utils \
        libvulkan1 \
        mesa-vulkan-drivers \
        libx11-dev \
        libxcursor-dev \
        libxi-dev \
        libxinerama-dev \
        libxrandr-dev  \
        mesa-common-dev \
        xorg-dev \
        && rm -rf /var/lib/apt/lists/*

    cd /opt/
    wget -O /opt/chroma_version.json https://api.github.com/repos/youngsm/chroma-lite/git/refs/heads/master
    git clone https://github.com/youngsm/chroma-lite
    mv chroma-lite chroma
    cd /opt/chroma/
    sed -i 's/VIRTUAL_ENV/CONDA_PREFIX/g' setup.py #use anaconda env instead

    # quick fix for EventViewer
    sed -i '741s/self\.i = len(self\.l-1)/self.i = len(self.l)-1/' chroma/camera.py
    python3 -m pip install -e .
    # below are extras for analyses
    python3 -m pip install -U trimesh numpy scipy scikit-learn h5py fire scikit-build cupy cuda-python pybind11
    python3 -m pip install git+https://github.com/CIDeR-ML/photonlib.git
    python3 -m pip install git+https://github.com/CIDeR-ML/siren-lartpc.git
    python3 -m pip install gdown
    python3 -m pip install rich
    cd /workspace/
    git clone https://github.com/youngsm/chroma-lar
    cd /workspace/chroma-lar/
    sh chroma_lar_env.sh
    python3 -m pip install -e .
    cd /workspace/
    python3 -m pip install git+https://github.com/CIDeR-ML/sirentv.git

%environment
    #For jupyter
    export PORT=8888
%startscript
    /bin/bash -l
